
PROJ = pong_app
ROOTDIR = ${SOS_DIR}

#DEFS += -DMICASB
SRCS += pong.c loader.c 

include $(ROOTDIR)/config/Makerules

vpath loader.c $(ROOTDIR)/modules/management/loader/
vpath pong.c ../../modules/pong/

