
# PROJ is the file name of your module.
PROJ = ping
ROOTDIR = ${SOS_DIR}

SUPPORTLIST = cyclops mica2 micaz xyz avrora cricket

ifdef INTERVAL
DEFS += -DPING_TIMER_INTERVAL=$(INTERVAL)
endif

include ${SOS_DIR}/modules/Makerules


